config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#管理者側
  devise_for :admins , controllers: {
     sessions: 'admins/sessions',
     passwords: 'admins/passwords',
     registrations: 'admins/registrations'
  }
  root to: 'homes#top'
  namespace :admin do
    resources :games
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only:[:show, :index]
  end

  # ユーザー側
  devise_for :users , controllers: {
     sessions: 'users/sessions',
     passwords: 'users/passwords',
     registrations: 'users/registrations'
  }
    root to: 'homes#top'
    #resources :post_comments, only:[:create, :destroy]
    # resources :users, only[:index, :show] #いいね機能
    get 'about' => 'homes#about'


  namespace :user do
    #get "users/unsubscribe" => "users#unsubscribe"
    resources :users, only:[:show, :edit, :update] do
      collection do
        get :unsubscribe
        patch :withdraw
      end
    end
    #patch "users/withdraw" => "users#withdraw"
   #掲示板機能のルーティング
    get 'topics/index'
    get 'topics/show/:id' => 'topics#show', as: :topics_show
    post 'topics/create' => 'topics#create'
	  delete 'topics/delete/:id' => 'topics#delete', as: :topic_delete
	  #新規書き込みのルーティング
	  post 'post/create' => 'post#create', as: :post_create
	  get 'search' => "search#search"
    ##### 問い合わせフォーム
    get 'inquiries' => 'inquiries#new'
    post 'inquiries/thanks' => 'inquiries#create'
    ##### 問い合わせ確認画面
    post 'inquiries/confirm' => 'inquiries#confirm'
    ##### 問い合わせ完了画面
    get 'inquiries/thanks' => 'inquiries#thanks'

    resources :games, only:[:show, :index] do
      resource :likes, only:[:create, :destroy]
        resources :reviews, only:[:index, :create, :destroy] do
          resource :likes, only:[:create, :destroy]
        end
      get 'download' => 'get#download'
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  #belongs_to :admin
  belongs_to :genre
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
  #ログインしているユーザーがこのゲームをいいねしているかどうかをチェックする記述
  
  def avg_score
    unless self.reviews.empty?
      reviews.average(:rate).round(1).to_f
    else
      0.0
    end
  end
  
  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:rate).round(1).to_f*100/5
    else
      0.0
    end
  end


  attachment :image

  validates :title, presence: true
  validates :introduction, presence: true
  validates :image, presence: true
  validates :body, presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :games

  validates :name, presence: true
end

app/models/inquiry.rb
class Inquiry  < ApplicationRecord

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :game, optional: true
  belongs_to :review, optional: true
  #1対他のアソシエーションが複数ある場合
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :game

  has_many :likes, dependent: :destroy

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  # validates :rate, numericality: {
  #   less_than_or_equal_to: 5,
  #   greater_than_or_equal_to: 1
  # }, presence: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :post_comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_reviews, through: :likes, source: :post
  has_many :topics, dependent: :destroy

  attachment :image

end

app/controllers/admin/games_controller.rb
class Admin::GamesController < ApplicationController
  def new
    @game = Game.new
  end

  def index
    @games = Game.all
    @games = Game.page(params[:page]).per(10)
  end

  def show
    @game = Game.find(params[:id])
  end

  def edit
    @game = Game.find(params[:id])
  end

  def create
    @game = Game.new(game_params)
    #byebug
    if @game.save!
      redirect_to admin_games_path(@game.id)
    else
      render :new
    end
  end

  def update
    @game = Game.find(params[:id])
   if @game.update(game_params)
     redirect_to admin_game_path(@game.id)
   else
     render :edit
   end
  end

  def destroy
    @game = Game.find(params[:id])
   if @game.destroy
     redirect_to admin_games_path
   else
     render :edit
   end
  end

  private
  def game_params
    params.require(:game).permit(:title, :introduction, :body, :image, :bonus_index, :genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters,if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :title])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @games = Game.order("updated_at").limit(3)
    #@new_games
    @all_ranks = Game.find(Like.group(:game_id).order('count(game_id) desc').limit(5).pluck(:game_id))
    @genres = Genre.all
  end

  def about
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :create]
  def index
    @post = Post.all
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end
  
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end
  
  private
  def post_params
    params.require(:post).permit(:contant)
  end
  
end

app/controllers/user/games_controller.rb
class User::GamesController < ApplicationController
  def index
    @game = Game.all
    @games = Game.page(params[:page]).per(10)
    @reviews = Review.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def counts(game)
    @count_game_reviews = game.game_reviews.count
  end

  def average(game)
    @average_game_reviews = Review.group(:game_id).average(:evaluation)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/download_helper.rb
module DownloadHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/postcomments_helper.rb
module PostcommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user/games_helper.rb
module User::GamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/games/edit.html.erb
<div class = "container">
 <h1>ゲーム編集</h1>
  <div class = "row">
    <%= form_with model:[:admin,@game], local:true do |f| %>
    <div class = "game-photo_image">
      <%= f.label :'画像:' %>
      <%= f.attachment_field :image %>
    </div>
    <div class = "game-title-table mb-3">
      <%= f.label :'ゲームタイトル:' %>
      <%= f.text_field :title, placeholder: 'タイトル', class: "form-control" %>
    </div>
    <div class = "genres-table mb-3">
      <%= f.label :'ジャンル:' %>
      <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "-- 選択してください --"  %>
    </div>
    <div class = "PR-table">
      <%= f.label :'簡潔PR:' %>
      <%= f.text_area :introduction, placeholder: 'PR', class: "form-control" %>
    </div>
    <div class = "PR-table">
      <%= f.label :'紹介文:' %>
      <%= f.text_area :body, placeholder: '紹介文', class: "form-control", rows: "8" %>
    </div>
    <div class = "bonus-table">
      <%= f.label :'特典:' %>
      <%= f.text_area :introduction, placeholder: '特典', class: "form-control", rows: "8" %>
    </div>
    <div class = "center">
      <%= f.submit :更新する, class: 'btn btn-success' %>
      <%= link_to "削除する", admin_game_path, method: :delete, class: 'btn btn-danger' %>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/games/index.html.erb
<div class = "container">
 <h1>アプリゲーム一覧</h1>
  <div class ="new-game-edit">
   <%= link_to "新しいゲームを投稿する", new_admin_game_path , class: 'btn btn-primary' %>
   <%= link_to "登録ユーザー一覧", admin_users_path, class: 'btn btn-success' %>
   <%= link_to "ジャンル追加へ", admin_genres_path, class: 'btn btn-danger' %>
  </div>
    <div class="row">
      <% @games.each do |game| %>
      <div class = 'card col-md-4'>
       <div class="card-img-top">
        <%= attachment_image_tag game,:image, class: 'img-fluid' %>
       </div>
       <div class="card-body">
        <h5 class="card-title">
          <%= game.title %>
        </h5>
        <p class="card-text">
          <%= game.introduction %>
        </p>
         <%= link_to "編集する", edit_admin_game_path(game.id), class: 'btn btn-success' %>
       </div>
      </div>
     <% end %>
    </div>
 <%= paginate @games %>
</div>

app/views/admin/games/new.html.erb
<div class = "container">
  <h1>ゲーム新規登録</h1>
   <div class = "row">
     <%= form_with url:admin_games_path, model:@game, local:true do |f| %>
    <div class = "game-photo_image">
      <%= f.label :'画像:' %>
      <%= f.attachment_field :image %>
    </div>
    <div class = "game-title-table">
      <%= f.label :'ゲームタイトル:' %>
      <%= f.text_field :title, placeholder: 'タイトル', class: "form-control" %>
    </div>
    <div class = "genres-table">
      <%= f.label :'ジャンル:' %>
      <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "-- 選択してください --"  %>
    </div>
    <div class = "PR-table">
      <%= f.label :'ゲームについて:' %>
      <%= f.text_field :introduction, placeholder: 'PR', class: "form-control" %>
    </div>
    <div class = "PR-table">
      <%= f.label :'紹介文:' %>
      <%= f.text_area :body, placeholder: '紹介文', class: "form-control", rows: "8"%>
    </div>
    <div class = "bonus-table">
      <%= f.label :'特典:' %>
      <%= f.text_area :bonus_index, placeholder: '特典', class: "form-control", rows: "8" %>
    </div>
    <div class = "center">
      <%= f.submit '投稿する', class: 'btn btn-success' %>
      <%= link_to 'アプリゲーム一覧へ', admin_games_path, class: 'btn btn-primary' %>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/games/show.html.erb
<div class = "container">
  <h1>ゲーム詳細</h1>
   <div class = "row">
    <div class = "card">
      <%= attachment_image_tag @game, :image, class: 'img-fluid' %></tr>
      <div class ="card-body">
       <h5 class="card-title">
          ゲームタイトル:<%= @game.title %>
       </h5>
       <h5 class ="card-genre">
          ジャンル:<%= @game.genre.name %>
       </h5>
       <h5 class = "card-PR">
          簡潔PR:<%= @game.introduction %>
       </h5>
        <h5 class = "card-text">
          紹介文:<%= @game.body %>
        </h5>
        <h5 class = "card-bonus">
          特典:<%= @game.bonus_index %>
        </h5>
        <div class = "center">
          <%= link_to "編集する", edit_admin_game_path(@game.id), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
   </div>
</div>